name: 'release-test'
on: # rebuild any PRs and main branch changes
  create

jobs:
  release: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: |
          npm install
      - run: |
          npm run all

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: create-release
        if: github.event.ref_type == 'tag'
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          changelogPaths: 'docs/changelog.en-US.md,docs/changelog.zh-CN.md'
          tagName: ${{ steps.get_version.outputs.VERSION }}
